// <auto-generated />
using System;
using System.Collections.Generic;
using CarparkInfo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarparkInfo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarparkDbContext))]
    [Migration("20260731102603_AddCarparkStaging")]
    partial class AddCarparkStaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CarparkInfo.Domain.Carparks.CarParkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_car_park_type_code");

                    b.ToTable("car_park_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SURFACE",
                            IsActive = true,
                            Name = "SURFACE CAR PARK"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MULTI_STOREY",
                            IsActive = true,
                            Name = "MULTI-STOREY CAR PARK"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BASEMENT",
                            IsActive = true,
                            Name = "BASEMENT CAR PARK"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SURFACE_MULTI_STOREY",
                            IsActive = true,
                            Name = "SURFACE/MULTI-STOREY CAR PARK"
                        },
                        new
                        {
                            Id = 5,
                            Code = "COVERED",
                            IsActive = true,
                            Name = "COVERED CAR PARK"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MECHANISED_AND_SURFACE",
                            IsActive = true,
                            Name = "MECHANISED AND SURFACE CAR PARK"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MECHANISED",
                            IsActive = true,
                            Name = "MECHANISED CAR PARK"
                        });
                });

            modelBuilder.Entity("CarparkInfo.Domain.Carparks.Carpark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("CarParkNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("car_park_no");

                    b.Property<int>("CarParkTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("car_park_type_id");

                    b.Property<int>("DeckCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deck_count");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at");

                    b.Property<int>("FreeParkingTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("free_parking_type_id");

                    b.Property<bool>("HasBasement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_basement");

                    b.Property<bool>("HasNightParking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_night_parking");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("LastJobRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_job_run_id");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("ParkingSystemTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parking_system_type_id");

                    b.Property<int>("ShortTermParkingTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("short_term_parking_type_id");

                    b.Property<string>("SourceRowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_row_hash");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "HeightRestriction", "CarparkInfo.Domain.Carparks.Carpark.HeightRestriction#HeightRestriction", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsRestricted")
                                .HasColumnType("INTEGER")
                                .HasColumnName("has_height_restriction");

                            b1.Property<decimal?>("MaximumVehicleHeightMetres")
                                .HasPrecision(4, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("gantry_height_m");

                            b1.Property<decimal>("RawSourceValue")
                                .HasPrecision(4, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("gantry_height_raw");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "CarparkInfo.Domain.Carparks.Carpark.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("longitude");

                            b1.Property<double>("Svy21X")
                                .HasPrecision(12, 4)
                                .HasColumnType("REAL")
                                .HasColumnName("svy21_x");

                            b1.Property<double>("Svy21Y")
                                .HasPrecision(12, 4)
                                .HasColumnType("REAL")
                                .HasColumnName("svy21_y");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CarParkNo")
                        .IsUnique()
                        .HasDatabaseName("ux_carpark_car_park_no");

                    b.HasIndex("CarParkTypeId");

                    b.HasIndex("FreeParkingTypeId");

                    b.HasIndex("ParkingSystemTypeId");

                    b.HasIndex("ShortTermParkingTypeId");

                    b.HasIndex("IsActive", "CarParkNo")
                        .HasDatabaseName("ix_carpark_keyset");

                    b.ToTable("carpark", (string)null);
                });

            modelBuilder.Entity("CarparkInfo.Domain.Carparks.FreeParkingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AppliesOnSundaysAndPublicHolidays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("applies_sun_and_ph");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsOffered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_offered");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_free_parking_type_code");

                    b.ToTable("free_parking_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesOnSundaysAndPublicHolidays = false,
                            Code = "NONE",
                            Description = "NO",
                            IsOffered = false
                        },
                        new
                        {
                            Id = 2,
                            AppliesOnSundaysAndPublicHolidays = true,
                            Code = "SUN_PH_0700_2230",
                            Description = "SUN & PH FR 7AM-10.30PM",
                            EndTime = new TimeOnly(22, 30, 0),
                            IsOffered = true,
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AppliesOnSundaysAndPublicHolidays = true,
                            Code = "SUN_PH_1300_2230",
                            Description = "SUN & PH FR 1PM-10.30PM",
                            EndTime = new TimeOnly(22, 30, 0),
                            IsOffered = true,
                            StartTime = new TimeOnly(13, 0, 0)
                        });
                });

            modelBuilder.Entity("CarparkInfo.Domain.Carparks.ParkingSystemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_parking_system_type_code");

                    b.ToTable("parking_system_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ELECTRONIC",
                            Name = "ELECTRONIC PARKING"
                        },
                        new
                        {
                            Id = 2,
                            Code = "COUPON",
                            Name = "COUPON PARKING"
                        });
                });

            modelBuilder.Entity("CarparkInfo.Domain.Carparks.ShortTermParkingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsWholeDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_whole_day");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_short_term_parking_type_code");

                    b.ToTable("short_term_parking_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WHOLE_DAY",
                            Description = "WHOLE DAY",
                            IsAvailable = true,
                            IsWholeDay = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "T0700_2230",
                            Description = "7AM-10.30PM",
                            EndTime = new TimeOnly(22, 30, 0),
                            IsAvailable = true,
                            IsWholeDay = false,
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Code = "NONE",
                            Description = "NO",
                            IsAvailable = false,
                            IsWholeDay = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "T0700_1900",
                            Description = "7AM-7PM",
                            EndTime = new TimeOnly(19, 0, 0),
                            IsAvailable = true,
                            IsWholeDay = false,
                            StartTime = new TimeOnly(7, 0, 0)
                        });
                });

            modelBuilder.Entity("CarparkInfo.Domain.Ingestion.CarparkStagingRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("CarParkNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("car_park_no");

                    b.Property<int>("CarParkTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("car_park_type_id");

                    b.Property<int>("DeckCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deck_count");

                    b.Property<int>("FreeParkingTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("free_parking_type_id");

                    b.Property<decimal?>("GantryHeightMetres")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("gantry_height_m");

                    b.Property<decimal>("GantryHeightRaw")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("gantry_height_raw");

                    b.Property<bool>("HasBasement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_basement");

                    b.Property<bool>("HasHeightRestriction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_height_restriction");

                    b.Property<bool>("HasNightParking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_night_parking");

                    b.Property<int>("JobRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_run_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_number");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<int>("ParkingSystemTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parking_system_type_id");

                    b.Property<int>("ShortTermParkingTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("short_term_parking_type_id");

                    b.Property<string>("SourceRowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_row_hash");

                    b.Property<double>("Svy21X")
                        .HasPrecision(12, 4)
                        .HasColumnType("REAL")
                        .HasColumnName("svy21_x");

                    b.Property<double>("Svy21Y")
                        .HasPrecision(12, 4)
                        .HasColumnType("REAL")
                        .HasColumnName("svy21_y");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId", "CarParkNo")
                        .HasDatabaseName("ix_staging_run_carpark");

                    b.ToTable("carpark_staging", (string)null);
                });

            modelBuilder.Entity("CarparkInfo.Domain.Ingestion.JobRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_summary");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("host_name");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_mode");

                    b.Property<int>("RecordsDeactivated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_deactivated");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_inserted");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_read");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_rejected");

                    b.Property<int>("RecordsUnchanged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_unchanged");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_updated");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique()
                        .HasDatabaseName("ux_job_run_file_hash")
                        .HasFilter("status = 'Succeeded'");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("ix_job_run_status");

                    b.ToTable("job_run", (string)null);
                });

            modelBuilder.Entity("CarparkInfo.Domain.Ingestion.JobRunError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CarParkNo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("car_park_no");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("FieldName")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("field_name");

                    b.Property<int>("JobRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_run_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_number");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("RawLine")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_line");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId", "Severity")
                        .HasDatabaseName("ix_job_run_error_run");

                    b.ToTable("job_run_error", (string)null);
                });

            modelBuilder.Entity("CarparkInfo.Domain.Users.Favourite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int>("CarparkId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("carpark_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "CarparkId");

                    b.HasIndex("CarparkId")
                        .HasDatabaseName("ix_favourite_park");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_favourite_user");

                    b.ToTable("user_favourite", (string)null);
                });

            modelBuilder.Entity("CarparkInfo.Domain.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<int?>("ReplacedById")
                        .HasColumnType("INTEGER")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("CarparkInfo.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("LockoutEndsAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("lockout_ends_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_email");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("CarparkInfo.Domain.Carparks.Carpark", b =>
                {
                    b.HasOne("CarparkInfo.Domain.Carparks.CarParkType", "CarParkType")
                        .WithMany()
                        .HasForeignKey("CarParkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarparkInfo.Domain.Carparks.FreeParkingType", "FreeParkingType")
                        .WithMany()
                        .HasForeignKey("FreeParkingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarparkInfo.Domain.Carparks.ParkingSystemType", "ParkingSystemType")
                        .WithMany()
                        .HasForeignKey("ParkingSystemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarparkInfo.Domain.Carparks.ShortTermParkingType", "ShortTermParkingType")
                        .WithMany()
                        .HasForeignKey("ShortTermParkingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarParkType");

                    b.Navigation("FreeParkingType");

                    b.Navigation("ParkingSystemType");

                    b.Navigation("ShortTermParkingType");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Ingestion.JobRunError", b =>
                {
                    b.HasOne("CarparkInfo.Domain.Ingestion.JobRun", "JobRun")
                        .WithMany("Errors")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Users.Favourite", b =>
                {
                    b.HasOne("CarparkInfo.Domain.Carparks.Carpark", "Carpark")
                        .WithMany()
                        .HasForeignKey("CarparkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarparkInfo.Domain.Users.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carpark");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("CarparkInfo.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Ingestion.JobRun", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("CarparkInfo.Domain.Users.User", b =>
                {
                    b.Navigation("Favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
